apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: noerelay
  labels:
    app: noerelay
    release: prometheus
spec:
  selector:
    matchLabels:
      app: noerelay
  endpoints:
  - port: http
    path: /metrics
    authorization:
      credentials:
        name: noerelay-secrets
        key: metrics-api-key
    interval: 30s
    scrapeTimeout: 10s
